### ISSUE TITLE
这个代码怎么样运行起来啊

### ISSUE THREAD

**Issue by lsl031** [boylegu/theory-D-V-HPFS#118]
请问这个代码是还运行在python2下吗，npm install时太多错误了，请问下怎么处理呢？
npm WARN deprecated core-js@2.6.10: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'E:\\js\\theory-D-V-HPFS-master\\theory-D-V-HPFS-master\\c12\\bejobs\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.16.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:208:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:208:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\python\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\python\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:419:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:449:11)
npm ERR! gyp ERR! stack     at Socket.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Pipe.<anonymous> (node:net:322:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\js\\theory-D-V-HPFS-master\\theory-D-V-HPFS-master\\c12\\bejobs\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\node-sass
npm ERR! gyp ERR! node -v v18.16.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lsl03\AppData\Local\npm-cache\_logs\2023-07-01T12_21_06_472Z-debug-0.log

**Comment by boylegu** [comment]
建议在linux操作系统上运行 ，windows环境不支持

发自我的 iPhone

在 2023年7月1日，20:29，lsl031 ***@***.***> 写道：

﻿

请问这个代码是还运行在python2下吗，npm install时太多错误了，请问下怎么处理呢？
npm WARN deprecated ***@***.***: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli 'C:\Program Files\nodejs\node.exe',
npm ERR! gyp verb cli 'E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\node-gyp\bin\node-gyp.js',
npm ERR! gyp verb cli 'rebuild',
npm ERR! gyp verb cli '--verbose',
npm ERR! gyp verb cli '--libsass_ext=',
npm ERR! gyp verb cli '--libsass_cflags=',
npm ERR! gyp verb cli '--libsass_ldflags=',
npm ERR! gyp verb cli '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using ***@***.***
npm ERR! gyp info using ***@***.*** | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb which failed Error: not found: python2
npm ERR! gyp verb which failed at getNotFoundError (E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\which\which.js:13:12)
npm ERR! gyp verb which failed at F (E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\which\which.js:68:19)
npm ERR! gyp verb which failed at E (E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\which\which.js:80:29)
npm ERR! gyp verb which failed at E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\which\which.js:89:16
npm ERR! gyp verb which failed at E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\isexe\index.js:42:5
npm ERR! gyp verb which failed at E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb which failed at FSReqCallback.oncomplete (node:fs:208:21)
npm ERR! gyp verb which failed python2 Error: not found: python2
npm ERR! gyp verb which failed at getNotFoundError (E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\which\which.js:13:12)
npm ERR! gyp verb which failed at F (E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\which\which.js:68:19)
npm ERR! gyp verb which failed at E (E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\which\which.js:80:29)
npm ERR! gyp verb which failed at E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\which\which.js:89:16
npm ERR! gyp verb which failed at E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\isexe\index.js:42:5
npm ERR! gyp verb which failed at E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb which failed at FSReqCallback.oncomplete (node:fs:208:21) {
npm ERR! gyp verb which failed code: 'ENOENT'
npm ERR! gyp verb which failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb which succeeded python C:\python\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\python\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack File "", line 1
npm ERR! gyp ERR! stack import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack at ChildProcess.exithandler (node:child_process:419:12)
npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! stack at Socket. (node:internal/child_process:449:11)
npm ERR! gyp ERR! stack at Socket.emit (node:events:513:28)
npm ERR! gyp ERR! stack at Pipe. (node:net:322:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\Program Files\nodejs\node.exe" "E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\node-gyp\bin\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd E:\js\theory-D-V-HPFS-master\theory-D-V-HPFS-master\c12\bejobs\node_modules\node-sass
npm ERR! gyp ERR! node -v v18.16.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\lsl03\AppData\Local\npm-cache_logs\2023-07-01T12_21_06_472Z-debug-0.log

**Comment by ddao** [comment]
ERR! System Windows_NT 10.0.22000

可以尝试一下方法：
npm config set prefix ‘文件夹路径’
npm config set cache ‘文件夹路径’


或者直接尝试 cnpm install
